# Generated by Django 5.0.6 on 2024-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldofactivity',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldofactivity',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldofactivity',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
