# Generated by Django 5.0.6 on 2024-05-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channels',
            new_name='Channel',
        ),
    ]
