# Generated by Django 5.0.6 on 2024-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLP', '0002_rename_channels_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(),
        ),
    ]
