# Generated by Django 5.0.6 on 2024-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLP', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagazedlp',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datagazedlp',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datagazedlp',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datagazedlp',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datagazedlp',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datagazedlp',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
