# Generated by Django 5.0.6 on 2024-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLP', '0005_parts_about_en_parts_about_ru_parts_about_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
