# Generated by Django 5.0.6 on 2024-06-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLP', '0007_channel_title_en_channel_title_ru_channel_title_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='title_uz',
        ),
    ]
