# Generated by Django 5.0.6 on 2024-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_certificate',
            old_name='cetificate',
            new_name='certificate',
        ),
        migrations.AddField(
            model_name='about_us',
            name='body_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='body_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='body_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_license',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_license',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_license',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company_license',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_license',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_license',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='our_certificate',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='our_certificate',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='our_certificate',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
