# Generated by Django 5.0.6 on 2024-06-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_rename_cetificate_our_certificate_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_certificate',
            name='title',
        ),
        migrations.RemoveField(
            model_name='our_certificate',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='our_certificate',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='our_certificate',
            name='title_uz',
        ),
    ]
